export const questions = [
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_1.png",
    A: "Renal artery",
    B: "Renal hilum",
    C: "Renal vein",
    D: "Kidney",
    E: "Ureter",
    F: "Urinary bladder",
    G: "Urethra",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_2.png",
    A: "Cortex",
    B: "Medulla",
    C: "Ureter",
    D: "Cortex",
    E: "Medulla",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_3.png",
    A: "Afferent arteriole",
    B: "Efferent arteriole",
    C: "Glomerulus",
    D: "Proximal convoluted tubule",
    E: "ASK PROFESSOR",
    F: "ASK PROFESSOR",
    G: "ASK PROFESSOR",
    H: "ASK PROFESSOR",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_4.png",
    A: "Urinary bladder",
    B: "Urethra",
    C: "Ovary",
    D: "Uterine tube",
    E: "Perimetrium",
    F: "Myometrium",
    G: "Endometrium",
    H: "Cervix",
    I: "Vagina",
    J: "Clitoris",
    K: "Uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_5.png",
    A: "Uterine tube",
    B: "Fimbriae",
    C: "Infundibulum",
    D: "Ampulla",
    E: "Isthmus",
    F: "Uterine part",
    G: "Perimetrium",
    H: "Myometrium",
    I: "Endometrium",
    J: "Cervical canal",
    K: "Body of uterus",
    L: "Uterine cavity",
    M: "Cervix",
    N: "Vagina",
    O: "Uterine tube",
    P: "Ovary",
    Q: "Broad ligament",
    R: "Ovarian ligament",
    S: "Round ligament of uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_6.png",
    A: "Corpus albicans",
    B: "Corpus luteum",
    C: "Corona radiata",
    D: "Secondary oocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_7.png",
    A: "Prostatic urethra",
    B: "Membranous urethra",
    C: "Spongy urethra",
    D: "Ductus deferens",
    E: "Epididymis",
    F: "Testes",
    G: "Penis",
    H: "Scrotum",
    I: "Corpus cavernosum",
    J: "Corpus spongiosum",
    K: "Seminal gland",
    L: "Prostate",
    M: "Cowper's gland (Bulbo-urethral gland)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_8.png",
    A: "Corpora cavernosa",
    B: "Urethra",
    C: "Corpus spongiosum",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_9.png",
    A: "Kidney",
    B: "Ureter",
    C: "Urinary bladder",
    D: "Penis",
    E: "Urethra",
    F: "Uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_10.png",
    A: "Epididymis",
    B: "Testes",
    C: "Urinary bladder",
    D: "Penis",
    E: "Ovary",
    F: "Urethra",
    G: "Uterine horns",
    H: "Uterine tube",
    I: "Body of uterus",
    J: "Vagina",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_11.png",
    1: "Renal vein",
    2: "Renal artery",
    10: "Ureter",
    11: "Renal pelvis",
    A: "Renal cortex",
    B: "Renal medulla (dark pink tissue) and renal pyramid (triangle shape)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_12.png",
    1: "Renal corpuscles",
    2: "Proximal convoluted tubule",
    3: "Distal convoluted tubule",
    4: "Collecting tubule",
    5: "Papillary duct",
    C: "Nephron loop (loop of Henle)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_13.png",
    1: "Afferent arteriole",
    2: "Glomerulus",
    3: "Efferent arteriole",
    4: "Podocytes",
    5: "Bowman's capsule (glomerular capsule)",
    6: "Proximal convoluted tubule",
    7: "Distal convoluted tubule",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_14.png",
    522: "Prostate gland",
    528: "Uteral orifice",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_15.png",
    519: "Seminal vesicle",
    521: "Ureter",
    522: "Prostate gland",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_16.png",
    519: "Seminal vesicle",
    520: "Ductus (vas) deferens",
    521: "Ureter",
    522: "Prostate gland",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_17.png",
    519: "Seminal vesicle",
    520: "Ductus (vas) deferens",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_18.png",
    503: "Urogenital diaphragm",
    504: "Cowper's gland",
    506: "Corpus spongiosum",
    507: "Corpora cavernosa",
    510: "Urethra",
    514: "Testes",
    515: "Epididymis",
    516: "Suspensory ligament",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_19.png",
    498: "Penis",
    499: "Scrotum",
    501: "Spermatic cord",
    502: "Cremaster muscle",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_20.png",
    475: "Urinary bladder",
    477: "Round ligament",
    478: "Isthmus of Fallopian tube",
    479: "Ovarian ligament",
    480: "Ovary",
    481: "Ampulla of Fallopian tube",
    482: "Fimbriae of Fallopian tube",
    483: "Broad ligament",
    484: "Uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_21.png",
    477: "Round ligament",
    478: "Isthmus of Fallopian tube",
    479: "Ovarian ligament",
    480: "Ovary",
    481: "Ampulla of Fallopian tube",
    482: "Fimbriae of Fallopian tube",
    483: "Broad ligament",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_22.png",
    475: "Urinary bladder",
    484: "Uterus",
    496: "Ureteral orifice",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_23.png",
    A: "Fallopian tube",
    C: "Perimetrium",
    D: "Myometrium",
    E: "Endometrium",
    F: "Cervical canal",
    G: "Vagina",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_24.png",
    A: "Perimetrium",
    B: "Myometrium",
    C: "Endometrium",
    D: "Uterus",
    E: "Cervix",
    F: "Labia majora",
    G: "Labia minora",
    H: "Vagina (vaginal canal)",
    I: "Right Fallopian tube",
    J: "Right ovary",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_25.png",
    A: "Prostate gland",
    B: "Corpus cavernosum",
    C: "Penis",
    D: "Corpus spongiosum",
    E: "Urethra",
    F: "Testes",
    G: "Ductus (vas) deferens",
  },
];
