export const questions = [
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_1.png",
    1: "Frontal belly of occipitofrontalis",
    2: "Orbicularis oculi",
    3: "Nasalis",
    4: "Zygomaticus minor",
    5: "Zygomaticus major",
    6: "Orbicularis oris",
    7: "Risorius",
    8: "Mentalis (cut)",
    9: "Temporoparietalis",
    10: "Levator labii superioris",
    11: "Masseter",
    12: "Buccinator",
    13: "Depressor anguli oris",
    14: "Sternocleidomastoid",
    15: "Trapezius",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_2.png",
    1: "Frontal belly of occipitofrontalis",
    2: "Orbicularis oculi",
    3: "Nasalis",
    4: "Zygomaticus minor",
    5: "Orbicularis oris",
    6: "Mentalis (cut)",
    8: "Depressor anguli oris",
    9: "Temporoparietalis",
    10: "Levator labii superioris",
    11: "Masseter",
    12: "Buccinator",
    13: "Depressor anguli oris",
    14: "Sternocleidomastoid",
    16: "Occipital belly of occipitofrontalis",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_3.png",
    17: "Omohyoid",
    18: "Sternocleidomastoid",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_4.png",
    15: "Trapezius",
    18: "Sternocleidomastoid",
    19: "Deltoid",
    20: "Pectoralis major",
    21: "Serratus anterior",
    22: "External oblique",
    25: "Pectoralis minor",
    26: "Internal oblique",
    27: "Rectus abdominis",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_5.png",
    21: "Serratus anterior",
    22: "External oblique",
    26: "Internal oblique",
    27: "Rectus abdominis",
    28: "Scalene (anterior)",
    29: "Scalene (middle)",
    30: "Scalene (posterior)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_6.png",
    15: "Trapezius",
    19: "Deltoid",
    21: "Serratus anterior",
    22: "External oblique",
    26: "Internal oblique",
    32: "Latissimus dorsi",
    33: "Levator scapulae",
  },
  { image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_7.png", 34: "Epidermis", 35: "Dermis", 36: "Subcutaneous tissue layer" },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_8.png",
    37: "Stratum corneum",
    38: "Stratum lucidum",
    39: "Stratum granulosum",
    40: "Stratum spinosum",
    41: "Stratum basale",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_4/lab_4_andrew_slide_9.png",
    42: "Sebaceous gland",
    43: "Arrector pili muscle",
    44: "Eccrine sweat gland",
    45: "Meissner's corpuscle",
    46: "Pacinian (lamellated) corpuscle",
    47: "Hair follicle",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_1.png",
    1: "Deltoid",
    2: "Coracobrachialis",
    3: "Teres major",
    4: "Biceps brachii, short head",
    5: "Biceps brachii, long head",
    6: "Supraspinatus",
    7: "Infraspinatus",
    8: "Teres minor",
    9: "Triceps brachii, long head",
    10: "Triceps brachii, lateral head",
    11: "Brachialis",
    12: "Brachioradialis",
    13: "Triceps brachii, medial head",
    14: "Pronator teres",
    15: "Flexor carpi radialis",
    16: "Palmaris longus",
    17: "Flexor carpi ulnaris",
    18: "Flexor digitorum superficialis",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_2.png",
    9: "Triceps brachii, long head",
    10: "Triceps brachii, lateral head",
    12: "Brachioradialis",
    14: "Pronator teres",
    17: "Flexor carpi ulnaris",
    19: "Anconeus",
    20: "Extensor digitorum",
    21: "Extensor carpi radialis longus",
    22: "Extensor carpi ulnaris",
    23: "Extensor carpi radialis brevis",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_3.png",
    11: "Brachialis",
    12: "Brachioradialis",
    14: "Pronator teres",
    15: "Flexor carpi radialis",
    16: "Palmaris longus",
    17: "Flexor carpi ulnaris",
    18: "Flexor digitorum superficialis",
    24: "Biceps brachii",
    25: "Triceps brachii, medial head",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_4.png",
    12: "Brachioradialis",
    17: "Flexor carpi ulnaris",
    19: "Anconeus",
    20: "Extensor digitorum",
    21: "Extensor carpi radialis longus",
    22: "Extensor carpi ulnaris",
    23: "Extensor carpi radialis brevis",
    24: "Biceps brachii",
    26: "Extensor digiti minimi",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_5.png",
    27: "Nasopharynx",
    28: "Oropharynx",
    29: "Epiglottis",
    30: "Nasal conchae",
    31: "Thyroid cartilage",
    32: "Cricoid cartilage",
    33: "Trachea",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_6.png",
    29: "Epiglottis",
    31: "Thyroid cartilage",
    32: "Cricoid cartilage",
    34: "Arytenoid cartilage",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_7.png",
    35: "Superior lobe",
    36: "Horizontal fissure",
    37: "Middle lobe",
    38: "Inferior lobe",
    39: "Cardiac notch",
    40: "Oblique fissure",
    41: "Right lung",
    42: "Left lung",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_5/lab_5_andrew_slide_8.png",
    43: "Septal cell",
    44: "Alveolar macrophage",
    45: "Squamous alveolar cell",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_1.png",
    1: "Piriformis",
    2: "Superior gemelius",
    3: "Obturator internus",
    4: "Inferior gemellus",
    5: "Quadratus femoris",
    6: "Gracilis",
    7: "Adductor magnus",
    8: "Biceps femoris (long head)",
    9: "Gluteus maximus (cut)",
    10: "Gluteus medius (cut)",
    11: "Gluteus minimus",
    12: "Tensor fasciae latae",
    13: "Adductor longus",
    14: "Sartorius",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_2.png",
    11: "Gluteus medius",
    12: "Tensor fasciae latae",
    13: "Adductor longus",
    14: "Sartorius",
    15: "Rectus femoris",
    16: "Vasus lateralis",
    17: "Semitendinosus",
    18: "Semimembranosus",
    19: "Biceps femoris, short head",
    20: "Medial head of gastrocnemius",
    21: "Lateral head of gastrocnemius",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_3.png",
    6: "Gracilis",
    7: "Adductor magnus",
    8: "Biceps femoris (long head)",
    9: "Gluteus maximus",
    10: "Gluteus medius",
    12: "Tensor fasciae latae",
    13: "Adductor longus",
    14: "Sartorius",
    15: "Rectus femoris",
    17: "Semitendinosus",
    19: "Biceps femoris, short head",
    22: "Popliteus",
    23: "Vastus lateralis",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_4.png",
    24: "Tibialis anterior",
    25: "Fibularis longus",
    26: "Extensor digitorum longus",
    27: "Peroneus = Fibularis",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_5.png",
    22: "Popliteus",
    25: "Fibularis longus",
    27: "Peroneus = Fibularis",
    28: "Gastrocnemius, medial head",
    29: "Gastrocnemius, lateral head",
    30: "Tibialis posterior",
    31: "Fibularis brevis",
    32: "Flexor digitorum longus",
    33: "Flexor hallucis longus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_6.png",
    20: "Medial head of gastrocnemius",
    21: "Gastrocnemius, lateral head",
    24: "Tibialis anterior",
    25: "Fibularis longus",
    27: "Peroneus = Fibularis",
    30: "Tibialis posterior",
    31: "Fibularis brevis",
    34: "Soleus",
    35: "Biceps femoris",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_6/lab_6_andrew_slide_7.png",
    40: "Major duodenal papilla",
    41: "Hepatopancreatic ampulla and sphincter",
    42: "Caudate lobe",
    43: "Left lobe",
    44: "Porta hepatis",
    45: "Right lobe",
    46: "Quadrate lobe",
  },
];
