export const questions = [
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_1.png",
    A: "Renal artery",
    B: "Renal hilum",
    C: "Renal vein",
    D: "Kidney",
    E: "Ureter",
    F: "Urinary bladder",
    G: "Urethra",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_2.png",
    A: "Cortex",
    B: "Medulla",
    C: "Ureter",
    D: "Cortex", // TODO Fix image
    E: "Medulla", // TODO Fix image
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_4.png",
    A: "Urinary bladder",
    B: "Urethra",
    C: "Ovary",
    D: "Uterine tube",
    E: "Perimetrium",
    F: "Myometrium",
    G: "Endometrium",
    H: "Cervix",
    I: "Vagina",
    J: "Clitoris",
    K: "Uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_5.png",
    A: "Uterine tube",
    B: "Fimbriae",
    C: "Infundibulum",
    D: "Ampulla",
    E: "Isthmus",
    F: "Uterine part",
    G: "Perimetrium",
    H: "Myometrium",
    I: "Endometrium",
    J: "Cervical canal",
    K: "Body of uterus",
    L: "Uterine cavity",
    M: "Cervix",
    N: "Vagina",
    O: "Uterine tube",
    P: "Ovary",
    Q: "Broad ligament",
    R: "Ovarian ligament",
    S: "Round ligament of uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_6.png",
    A: "Corpus albicans",
    B: "Corpus luteum",
    C: "Corona radiata",
    D: "Secondary oocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_7.png",
    A: "Prostatic urethra",
    B: "Membranous urethra",
    C: "Spongy urethra",
    D: "Ductus deferens",
    E: "Epididymis",
    F: "Testes",
    G: "Penis",
    H: "Scrotum",
    I: "Corpus cavernosum",
    J: "Corpus spongiosum",
    K: "Seminal gland",
    L: "Prostate",
    M: "Cowper's gland (bulbo-urethral gland)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_8.png",
    A: "Corpora cavernosa",
    B: "Urethra",
    C: "Corpus spongiosum",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_9.png",
    A: "Kidney",
    B: "Ureter",
    C: "Urinary bladder",
    D: "Penis",
    E: "Urethra",
    F: "Uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_10.png",
    A: "Epididymis",
    B: "Testes",
    C: "Urinary bladder",
    D: "Penis",
    E: "Ovary",
    F: "Urethra",
    G: "Uterine horns",
    H: "Uterine tube",
    I: "Body of uterus",
    J: "Vagina",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_11.png",
    1: "Renal vein",
    2: "Renal artery",
    10: "Ureter",
    11: "Renal pelvis",
    A: "Renal cortex",
    B: "Renal medulla (dark pink tissue) and renal pyramid (triangle shape)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_12.png",
    1: "Renal corpuscle",
    2: "Proximal convoluted tubule",
    3: "Distal convoluted tubule",
    4: "Collecting tubule",
    5: "Papillary duct",
    C: "Nephron loop (loop of Henle)",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_13.png",
    1: "Afferent arteriole",
    2: "Glomerulus",
    3: "Efferent arteriole",
    4: "Podocyte",
    5: "Bowman's capsule (glomerular capsule)",
    6: "Proximal convoluted tubule",
    7: "Distal convoluted tubule",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_14.png",
    522: "Prostate gland",
    528: "Uteral orifice",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_15.png",
    519: "Seminal vesicle",
    521: "Ureter",
    522: "Prostate gland",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_16.png",
    519: "Seminal vesicle",
    520: "Ductus (vas) deferens",
    521: "Ureter",
    522: "Prostate gland",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_17.png",
    519: "Seminal vesicle",
    520: "Ductus (vas) deferens",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_18.png",
    503: "Urogenital diaphragm",
    504: "Cowper's gland",
    506: "Corpus spongiosum",
    507: "Corpora cavernosa",
    510: "Urethra",
    514: "Testes",
    515: "Epididymis",
    516: "Suspensory ligament",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_19.png",
    498: "Penis",
    499: "Scrotum",
    501: "Spermatic cord",
    502: "Cremaster muscle",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_20.png",
    475: "Urinary bladder",
    477: "Round ligament",
    478: "Isthmus of Fallopian tube",
    479: "Ovarian ligament",
    480: "Ovary",
    481: "Ampulla of Fallopian tube",
    482: "Fimbriae of Fallopian tube",
    483: "Broad ligament",
    484: "Uterus",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_21.png",
    477: "Round ligament",
    478: "Isthmus of Fallopian tube",
    479: "Ovarian ligament",
    480: "Ovary",
    481: "Ampulla of Fallopian tube",
    482: "Fimbriae of Fallopian tube",
    483: "Broad ligament",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_22.png",
    475: "Urinary bladder",
    484: "Uterus",
    496: "Ureteral orifice",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_23.png",
    A: "Fallopian tube",
    C: "Perimetrium",
    D: "Myometrium",
    E: "Endometrium",
    F: "Cervical canal",
    G: "Vagina",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_24.png",
    A: "Perimetrium",
    B: "Myometrium",
    C: "Endometrium",
    D: "Uterus",
    E: "Cervix",
    F: "Labia majora",
    G: "Labia minora",
    H: "Vagina (vaginal canal)",
    I: "Right Fallopian tube",
    J: "Right ovary",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_7/lab_7_slide_25.png",
    A: "Prostate gland",
    B: "Corpus cavernosum",
    C: "Penis",
    D: "Corpus spongiosum",
    E: "Urethra",
    F: "Testes",
    G: "Ductus (vas) deferens",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_1.png",
    A: "Pulmonary arteries",
    B: "Capillaries",
    C: "Pulmonary veins",
    D: "Right atrium",
    E: "Right ventricle",
    F: "Systemic arteries",
    G: "Left atrium",
    H: "Left ventricle",
    I: "Systemic veins",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_2.png",
    A: "Right atrium",
    B: "Right ventricle",
    C: "Left atrium",
    D: "Left ventricle",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_3.png",
    A: "Left atrium",
    B: "Left ventricle",
    C: "Right atrium",
    D: "Right ventricle",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_4.png",
    A: "Right atrium",
    B: "Right ventricle",
    C: "Left atrium",
    D: "Left ventricle",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_5.png",
    263: "Right atrium",
    264: "Left atrium",
    270: "Right coronary artery",
    271: "Anterior cardiac veins",
    272: "Greater cardiac vein",
    273: "Anterior interventricular branch of left coronary artery",
    280: "Superior vena cava",
    281: "Pulmonary artery",
    288: "Aortic arch",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_6.png",
    264: "Left atrium",
    266: "Left ventricle",
    272: "Greater cardiac vein",
    279: "Posterior vein",
    280: "Superior vena cava",
    281: "Pulmonary artery",
    284: "Left pulmonary vein",
    288: "Aortic arch",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_7.png",
    275: "Coronary sinus",
    277: "Middle cardiac vein",
    282: "Pulmonary artery",
    284: "Left pulmonary vein",
    286: "Inferior vena cava",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_8.png",
    263: "Right atrium",
    271: "Anterior cardiac vein",
    280: "Superior vena cava",
    283: "Pulmonary artery",
    285: "Right pulmonary vein",
    286: "Inferior vena cava",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_9.png",
    263: "Right atrium",
    264: "Left atrium",
    265: "Right ventricle",
    266: "Left ventricle",
    280: "Superior vena cava",
    281: "Pulmonary artery",
    287: "Ascending aorta", // TODO start here
    288: "Aortic arch",
    291: "Aortic valve",
    293: "Tricuspid valve",
    294: "Chordae tendineae (connects to papillary muscles)",
    295: "Interventricular septum",
    296: "Bicuspid valve",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_10_test.png",
    237: "Right internal jugular vein",
    238: "Right common carotid artery",
    239: "Right subclavian vein",
    240: "Right brachiocephalic vein",
    241: "Left brachiocephalic vein",
    242: "Brachiocephalic trunk",
    243: "Left subclavian vein",
    244: "Left subclavian artery",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_11.png",
    318: "Abdominal aorta",
    319: "Left inferior phrenic artery",
    320: "Right inferior phrenic artery",
    322: "Left superior suprarenal artery",
    323: "Right superior suprarenal artery",
    324: "Celiac trunk",
    325: "Splenic artery",
    326: "Hepatic artery",
    330: "Splenic vein",
    A: "Hepatic portal vein",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_12.png",
    350: "Superior mesenteric artery",
    351: "Superior mesenteric vein",
    352: "Inferior pancreaticoduodenal artery",
    365: "Left common iliac vein",
    366: "Right common iliac vein",
    367: "Left internal iliac vein",
    368: "Bifurcation of abdmonial aorta",
    369: "Right common iliac artery",
    370: "Right internal iliac artery",
    371: "Left common iliac artery",
    372: "Left internal liliac artery",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_13.png",
    A: "Immature neutrophil",
    B: "Lymphocyte",
    C: "Monocyte",
    D: "Eosinophil",
    E: "Neutrophil",
    F: "Basophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_14.png",
    A: "Basophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_15.png",
    A: "Basophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_16.png",
    A: "Basophil",
    B: "Lymphocyte",
    C: "Monocyte",
    D: "Eosinophil",
    E: "Immature neutrophil",
    F: "Neutrophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_17.png",
    A: "Eosinophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_18.png",
    A: "Lymphocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_19.png",
    A: "Neutrophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_20.png",
    A: "Neutrophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_21.png",
    A: "Eosinophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_22.png",
    A: "Eosinophil",
    B: "Neutrophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_23.png",
    A: "Monocyte",
    B: "Lymphocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_24.png",
    A: "Lymphocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_25.png",
    A: "Monocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_26.png",
    A: "Neutrophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_27.png",
    A: "Eosinophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_28.png",
    A: "Basophil",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_29.png",
    A: "Lymphocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_30.png",
    A: "Monocyte",
  },
  {
    image: "https://boej6iprvajfuxis.public.blob.vercel-storage.com/lab_8/lab_8_slide_31.png",
    A: "Sickle cell anemia",
  },
];
